test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_valid_HR
  wrapper:
    name: sr-cut-downsampled-test
    args:
      test_scale: 30
  batch_size: 1
eval_type: div2k-30
